name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy to aws
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: deployment
<<<<<<< HEAD
        run: ./deploy.sh
=======
        run: chmod +x ./deploy.sh
>>>>>>> 34e46573f945ad3610d4661f35ae6e236bb1a9d2
